import React, { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Bike, CarFront, ChevronRight, Filter, Search, SlidersHorizontal, Star } from 'lucide-react';
import { vehicleAPI } from './api/vehicles';

export default function Explore() {
  const [params] = useSearchParams();
  const [vehicles, setVehicles] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [query, setQuery] = useState(params.get('q') || ''); const [type, setType] = useState(params.get('type') || 'all');
  const [fuel, setFuel] = useState('all'); const [maxPrice, setMaxPrice] = useState(''); const [sort, setSort] = useState('recommended'); const [filters, setFilters] = useState(false);
  useEffect(() => { let active = true; setLoading(true); vehicleAPI.getVehicles({ limit: 60, search: query || undefined, type: type !== 'all' ? type : undefined }).then(d => active && setVehicles(d.vehicles || d.data || [])).catch(e => active && setError(e.message || 'Unable to load fleet')).finally(() => active && setLoading(false)); return () => { active = false; }; }, [query, type]);
  const shown = useMemo(() => { const r = vehicles.filter(v => { const p = Number(v.pricePerDay ?? v.basePrice ?? v.dailyRate ?? 0); return (!maxPrice || p <= Number(maxPrice)) && (fuel === 'all' || String(v.fuelType || '').toLowerCase() === fuel.toLowerCase()); }); return r.sort((a,b) => sort === 'price-low' ? Number(a.pricePerDay ?? a.basePrice ?? 0)-Number(b.pricePerDay ?? b.basePrice ?? 0) : sort === 'price-high' ? Number(b.pricePerDay ?? b.basePrice ?? 0)-Number(a.pricePerDay ?? a.basePrice ?? 0) : 0); }, [vehicles,fuel,maxPrice,sort]);
  const clear = () => { setQuery(''); setType('all'); setFuel('all'); setMaxPrice(''); };
  return <main className="min-h-screen bg-[#08090b] text-white pt-20">
    <section className="border-b border-white/10 bg-[radial-gradient(circle_at_70%_0%,rgba(245,158,11,.13),transparent_35%)]"><div className="max-w-7xl mx-auto px-6 lg:px-10 py-14">
      <p className="text-xs uppercase tracking-[.25em] text-amber-300">Ride Flex / Explore</p><h1 className="mt-3 text-5xl md:text-6xl font-semibold tracking-[-.04em]">Find your next ride.</h1>
      <p className="mt-4 text-white/45 max-w-xl">Verified vehicles from trusted rental partners, with flexible pickup and delivery where available.</p>
      <div className="mt-8 flex items-center gap-2 max-w-xl rounded-2xl border border-white/10 bg-white/[.04] px-4 py-3"><Search size={18} className="text-white/35"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search bike, scooter, car..." className="bg-transparent outline-none w-full text-sm placeholder:text-white/30"/></div>
      <div className="mt-6 flex flex-wrap gap-2">{[['all','All'],['bike','Bikes'],['scooter','Scooters'],['car','Cars']].map(([v,l]) => <button key={v} onClick={()=>setType(v)} className={'px-4 py-2.5 rounded-xl text-sm border '+(type===v?'bg-white text-black border-white':'border-white/10 text-white/55')}>{v==='car'?<CarFront size={15} className="inline mr-2"/>:v!=='all'?<Bike size={15} className="inline mr-2"/>:null}{l}</button>)}<button onClick={()=>setFilters(!filters)} className="ml-auto px-4 py-2.5 rounded-xl text-sm border border-white/10 text-white/60"><SlidersHorizontal size={15} className="inline mr-2"/>Filters</button></div>
      {filters && <div className="mt-4 grid md:grid-cols-3 gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-4"><label className="text-xs text-white/40">Fuel<select value={fuel} onChange={e=>setFuel(e.target.value)} className="mt-2 w-full rounded-xl bg-black/30 border border-white/10 p-3 text-sm text-white"><option value="all">All fuel types</option><option>Petrol</option><option>Electric</option></select></label><label className="text-xs text-white/40">Maximum daily price<input type="number" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="₹" className="mt-2 w-full rounded-xl bg-black/30 border border-white/10 p-3 text-sm outline-none text-white"/></label><label className="text-xs text-white/40">Sort<select value={sort} onChange={e=>setSort(e.target.value)} className="mt-2 w-full rounded-xl bg-black/30 border border-white/10 p-3 text-sm text-white"><option value="recommended">Recommended</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label></div>}
    </div></section>
    <section className="max-w-7xl mx-auto px-6 lg:px-10 py-12">{error&&<p className="mb-5 text-red-300">{error}</p>}{loading?<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{[1,2,3].map(i=><div key={i} className="h-[430px] rounded-[1.75rem] bg-white/[.04] animate-pulse"/>)}</div>:shown.length===0?<div className="rounded-[2rem] border border-white/10 bg-white/[.03] p-16 text-center"><Filter className="mx-auto text-white/25"/><h2 className="mt-5 text-2xl font-semibold">No matching rides</h2><p className="mt-2 text-white/40">Try a broader search or remove a filter.</p><button onClick={clear} className="mt-6 rounded-xl bg-white text-black px-5 py-3 font-semibold">Clear filters</button></div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{shown.map(v=>{const id=v._id||v.id;const image=v.images?.[0]?.url||v.images?.[0]||v.image;const price=v.pricePerDay??v.basePrice??v.dailyRate??0;const name=v.name||v.vehicleName||((v.brand||'')+' '+(v.model||'')).trim()||'Premium ride';return <Link to={'/vehicles/'+id} key={id} className="group overflow-hidden rounded-[1.75rem] border border-white/10 bg-white/[.035] hover:bg-white/[.055] transition"><div className="h-60 overflow-hidden bg-white/5">{image&&<img src={image} alt={name} className="w-full h-full object-cover group-hover:scale-105 transition duration-700"/>}</div><div className="p-5"><div className="flex justify-between gap-4"><div><h3 className="text-xl font-semibold">{name}</h3><p className="mt-1 text-sm text-white/40">{v.location?.city||v.city||'Nearby'} · {v.fuelType||'Flexible fuel'}</p></div><div className="text-right"><p className="text-lg font-semibold">₹{Number(price).toLocaleString('en-IN')}</p><p className="text-xs text-white/35">per day</p></div></div><div className="mt-5 pt-4 border-t border-white/10 flex justify-between text-sm"><span className="text-white/45"><Star size={14} className="inline mr-1 text-amber-300"/>{v.rating||'New'}</span><span className="text-amber-300 font-semibold">View ride <ChevronRight size={15} className="inline"/></span></div></div></Link>})}</div>}</section>
  </main>;
}