import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CalendarDays, Check, Fuel, MapPin, ShieldCheck, Star } from 'lucide-react';
import { vehicleAPI } from './api/vehicles';
import { useAuth } from './AuthContext';

export default function VehicleDetails(){ const {id}=useParams(); const navigate=useNavigate(); const {user}=useAuth(); const [v,setV]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [start,setStart]=useState(''); const [end,setEnd]=useState('');
 useEffect(()=>{vehicleAPI.getVehicleById(id).then(d=>setV(d.vehicle||d.data||d)).catch(e=>setError(e.message||'Unable to load vehicle')).finally(()=>setLoading(false))},[id]);
 if(loading)return <main className="min-h-screen pt-32 bg-[#08090b] text-white"><div className="max-w-7xl mx-auto px-6 h-[500px] rounded-[2rem] bg-white/[.04] animate-pulse"/></main>;
 if(error||!v)return <main className="min-h-screen pt-32 bg-[#08090b] text-white text-center"><p className="text-red-300">{error||'Vehicle not found'}</p></main>;
 const price=Number(v.pricePerDay??v.basePrice??v.dailyRate??0); const image=v.images?.[0]?.url||v.images?.[0]||v.image; const name=v.name||v.vehicleName||((v.brand||'')+' '+(v.model||'')).trim()||'Premium ride';
 const reserve=()=>{if(!user)return navigate('/auth');if(!start||!end)return setError('Choose pickup and return dates.');navigate('/booking?vehicle='+id+'&start='+start+'&end='+end)};
 return <main className="min-h-screen pt-28 pb-20 bg-[#08090b] text-white"><div className="max-w-7xl mx-auto px-6 lg:px-10"><button onClick={()=>navigate(-1)} className="text-white/45 mb-7"><ArrowLeft size={16} className="inline mr-2"/>Back</button><div className="grid lg:grid-cols-[1.25fr_.75fr] gap-7"><div><div className="h-[520px] rounded-[2rem] overflow-hidden border border-white/10 bg-white/[.03]">{image&&<img src={image} alt={name} className="w-full h-full object-cover"/>}</div><p className="mt-7 text-xs uppercase tracking-[.25em] text-amber-300">{v.vehicleType||'Vehicle'}</p><h1 className="mt-2 text-5xl font-semibold">{name}</h1><p className="mt-3 text-white/45"><MapPin size={15} className="inline mr-2"/>{v.location?.city||v.city||'Location available after selection'}</p></div><aside className="lg:sticky lg:top-28 h-fit rounded-[2rem] border border-white/10 bg-white/[.045] p-6"><div className="flex justify-between"><div><p className="text-sm text-white/40">Daily rental</p><p className="text-3xl font-semibold">₹{price.toLocaleString('en-IN')}</p></div><span className="text-sm text-white/50"><Star size={14} className="inline text-amber-300 mr-1"/>{v.rating||'New'}</span></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-black/20 p-3"><Fuel size={15} className="text-amber-300"/><p className="mt-2 text-xs text-white/35">Fuel</p><p className="mt-1 text-sm">{v.fuelType||'—'}</p></div><div className="rounded-xl bg-black/20 p-3"><ShieldCheck size={15} className="text-amber-300"/><p className="mt-2 text-xs text-white/35">Trust</p><p className="mt-1 text-sm">Verified partner</p></div></div><div className="mt-7 grid grid-cols-2 gap-3"><label className="text-xs text-white/40">Pickup<input type="date" value={start} onChange={e=>setStart(e.target.value)} className="mt-2 w-full rounded-xl bg-black/30 border border-white/10 p-3 text-sm text-white"/></label><label className="text-xs text-white/40">Return<input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="mt-2 w-full rounded-xl bg-black/30 border border-white/10 p-3 text-sm text-white"/></label></div>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}<button onClick={reserve} className="mt-5 w-full rounded-xl bg-white text-black py-4 font-semibold hover:bg-amber-100"><CalendarDays size={17} className="inline mr-2"/>Continue to booking</button><p className="mt-4 text-xs text-white/30"><Check size={13} className="inline mr-1 text-emerald-300"/>Subject to availability and verification.</p></aside></div></div></main>;
}